INSERT INTO countries_vat (country, vat, year, currency, currency_symbol) VALUES
('Austria',                 20.0,   2025,   'Euro',                                       '€'),
('Belgium',                 21.0,   2025,   'Euro',                                       '€'),
('Bulgaria',                20.0,   2025,   'Bulgarian lev',                              'лв'),
('Croatia',                 25.0,   2025,   'Euro',                                       '€'),
('Cyprus',                  19.0,   2025,   'Euro',                                       '€'),
('Czech Republic',          21.0,   2025,   'Czech koruna',                               'Kč'),
('Denmark',                 25.0,   2025,   'Danish krone',                               'kr'),
('Estonia',                 22.0,   2025,   'Euro',                                       '€'),
('Finland',                 25.5,   2025,   'Euro',                                       '€'),
('France',                  20.0,   2025,   'Euro',                                       '€'),
('Germany',                 19.0,   2025,   'Euro',                                       '€'),
('Greece',                  24.0,   2025,   'Euro',                                       '€'),
('Hungary',                 27.0,   2025,   'Hungarian forint',                           'Ft'),
('Ireland',                 23.0,   2025,   'Euro',                                       '€'),
('Italy',                   22.0,   2025,   'Euro',                                       '€'),
('Latvia',                  21.0,   2025,   'Euro',                                       '€'),
('Lithuania',               21.0,   2025,   'Euro',                                       '€'),
('Luxembourg',              17.0,   2025,   'Euro',                                       '€'),
('Malta',                   18.0,   2025,   'Euro',                                       '€'),
('Netherlands',             21.0,   2025,   'Euro',                                       '€'),
('Poland',                  23.0,   2025,   'Polish złoty',                               'zł'),
('Portugal',                23.0,   2025,   'Euro',                                       '€'),
('Romania',                 19.0,   2025,   'Romanian leu',                               'lei'),
('Slovakia',                23.0,   2025,   'Euro',                                       '€'),
('Slovenia',                22.0,   2025,   'Euro',                                       '€'),
('Spain',                   21.0,   2025,   'Euro',                                       '€'),
('Sweden',                  25.0,   2025,   'Swedish krona',                              'kr'),
('United Kingdom',          20.0,   2025,   'Pound sterling',                             '£'),
('Norway',                  25.0,   2025,   'Norwegian krone',                            'kr'),
('Switzerland',             8.1,    2025,   'Swiss franc',                                'CHF'),
('Iceland',                 24.0,   2025,   'Icelandic króna',                            'kr'),
('Liechtenstein',           7.7,    2025,   'Swiss franc',                                'CHF'),
('Monaco',                  20.0,   2025,   'Euro',                                       '€'),
('San Marino',              22.0,   2025,   'Euro',                                       '€'),
('Andorra',                 4.5,    2025,   'Euro',                                       '€'),
('Albania',                 20.0,   2025,   'Albanian lek',                               'L'),
('Bosnia and Herzegovina',  17.0,   2025,   'Bosnia and Herzegovina convertible mark',    'KM'),
('North Macedonia',         18.0,   2025,   'Macedonian denar',                           'ден'),
('Moldova',                 20.0,   2025,   'Moldovan leu',                               'L'),
('Montenegro',              21.0,   2025,   'Euro',                                       '€'),
('Serbia',                  20.0,   2025,   'Serbian dinar',                              'дин'),
('Turkey',                  20.0,   2025,   'Turkish lira',                               '₺'),
('Ukraine',                 20.0,   2025,   'Ukrainian hryvnia',                          '₴'),
('Russia',                  20.0,   2025,   'Russian ruble',                              '₽'),
('Belarus',                 20.0,   2025,   'Belarusian ruble',                           'Br'),
('Kosovo',                  18.0,   2025,   'Euro',                                       '€');
