services:
  supplements-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/supplements-api
      - supplements_api_node_modules:/supplements-api/node_modules
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: supplements_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    container_name: supplements-cnt
    command: npm run dev
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supplements_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    container_name: supplements-db

volumes:
  db:
  supplements_api_node_modules: