CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_reset_1 VARCHAR(255) DEFAULT NULL,
  password_reset_2 VARCHAR(255) DEFAULT NULL,
  password_reset_3 VARCHAR(255) DEFAULT NULL,
  password_reset_4 VARCHAR(255) DEFAULT NULL,
  password_reset_date TIMESTAMP NULL DEFAULT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT(1) DEFAULT 0,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);